fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: App\Entity\User
    service:                               # this lines
          mailer: fos_user.mailer.twig_swift 
    from_email:
        address: "test@localhost.com"
        sender_name: "My Name"
    resetting:
        email:
            from_email: 
                address: "test@localhost.com"
                sender_name: "My Name"